export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE'
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE'

export const SHOW_GLOBAL_LOADER='SHOW_GLOBAL_LOADER'
export const HIDE_GLOBAL_LOADER='HIDE_GLOBAL_LOADER'
